### ISSUE TITLE
Source code for custom CSS?

### ISSUE THREAD

**Issue by bergstar** [tailwindtoolbox/Landing-Page#1]
Could you please provide custom CSS used in:
https://unpkg.com/tailwindcss@next/dist/tailwind.min.css

This is needed since template is not working with stock tailwind.min.css from CDN
It also hinders extending theme as most CSS has to be re-created.

**Comment by tailwindtoolbox** [comment]
That is the official hosted version of the Tailwind v1 beta.
https://next.tailwindcss.com/docs/installation#using-tailwind-via-cdn

What in particular isn't working?

**Comment by bergstar** [comment]
Sorry, I was using older 0.7.4 version of Tailwind CSS.

**Comment by tailwindtoolbox** [comment]
Is it working fine now you've switched over?

**Comment by bergstar** [comment]
Yes, it does - everything is okay with 1.0.0 version. Thank you
