### ISSUE TITLE
Many of your demos are broken because TailwindCSS stopped UNPKG support

### ISSUE THREAD

**Issue by adam993** [tailwindtoolbox/Landing-Page#19]
Many of your examples are not working because TailwindCSS stopped UNPKG support.

For example, take a look at your landing page demo from this repo, it's completely broken. 

For more info see this issue I posted on Tailwind repo:

https://github.com/tailwindlabs/tailwindcss/issues/6355

**Comment by tailwindtoolbox** [comment]
Hi @adam993 

Thanks for the message - I've changed them all to use the v2 CDN so they are still working for now...

I've not had a chance to look at them for using with v3 + the new JS CDN yet (don't think I'll have time until the new year)

**Comment by tailwindtoolbox** [comment]
It should work in v3  (maybe with a few teething issues) if you switch the css line from:
 `-`  `<link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>`
`+`  `<script src="https://cdn.tailwindcss.com"></script>`

**Comment by richardmtheobald** [comment]
Is there any way I can just get a copy of the minified tailwind 2.2.19? The reason I was using unpkg in the first place is because I do not want a CLI. And the new CDN is pretty slow and doesn't seem to work the same.

**Comment by tailwindtoolbox** [comment]
Hey, you can just navigate to https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css and then file save as?

Or is it something different you are after?

**Comment by richardmtheobald** [comment]
No, this will work. Unpkg must have been down earlier when I was debugging this, but it seems to be back now.

**Comment by tailwindtoolbox** [comment]
Good luck with your project 👍🏽
