### ISSUE TITLE
Missing hero.png in project directory

### ISSUE THREAD

**Issue by jeanbauer** [tailwindtoolbox/Landing-Page#2]
On line 92 it looks for a hero.png: https://github.com/tailwindtoolbox/Landing-Page/blob/master/landing.html#L92

**Comment by hubertlepicki** [comment]
@jeanbauer I very much like the template and would probably want to use it *including* the hero.png but I am unsure how this image is licensed and where is coming from. Do you know and can provide such information? My google-fu is failing me to find the source of the image...

**Comment by tailwindtoolbox** [comment]
@hubertlepicki  - the image is from https://www.freepik.com/free-vector/isometric-education-illustration_3940819.htm#page=1&query=isometric%20plane&position=1

It's free to use as long as you attribute.  I will update the page to include this.

**Comment by hubertlepicki** [comment]
Right, *or* I can get a freepik subscription then I don't have to attribute.

Thanks for clarifying this.
