### ISSUE TITLE
Duplicated attributes `fill` breaks my build

### ISSUE THREAD

**Issue by quantuminformation** [tailwindtoolbox/Landing-Page#6]
Any reason why we need this?				

	<rect fill="#2a2a31" x="16.539" y="425.626" width="479.767" height="50.502" transform="matrix(1,0,0,1,0,0)" fill="rgb(0,0,0)" />

my rollup builds gives: `Attributes need to be unique`

**Comment by quantuminformation** [comment]
Also, I'm not seeing the slide in functions working. They run but nothing is visible.

**Comment by quantuminformation** [comment]
and this icon is hard to see on mobile:

<img width="203" alt="Screenshot 2019-11-05 at 18 42 43" src="https://user-images.githubusercontent.com/216566/68235991-3191f000-fffc-11e9-93a2-bcd911c580d2.png">

**Comment by tailwindtoolbox** [comment]
Hi there.

That line is the black underline for the temp svg logo. You can safely remove that and replace it with your own logo as it's just there as a temporary icon until you update it with your own logo!

Re: slide in - there is no slide in function?  There is a badly worded comment in the JS saying slide in, but that's referring to the white bg which is applied as you scroll down.
Feel free to add some animation classes (I believe some are coming soon for Tailwind, Adam is working on them) and then you can apply them using header.classList.add(...)

Re: nav icon, I recently updated it, so please refresh your branch.  But again, just tweak the classes of the svg to make it suit your design.
![image](https://user-images.githubusercontent.com/43570497/68288246-f6370600-007b-11ea-8984-9ae8f9dfd5b5.png)

Cheers for checking out the template! 👍
